vector:
	cd .. && \
	g++ -c vector.cpp && \
	g++ -c generating.cpp && \
	g++ -c Time.cpp && \
	g++ -o vector 2_uzduotis_vector.cpp vector.o Time.o && \
	g++ -o generavimas generavimas.cpp generating.o && \
	./generavimas && \
	./vector
valymas:
	cd .. && \
	rm *.o blogi.txt geri.txt mokiniai1.txt mokiniai2.txt mokiniai3.txt mokiniai4.txt mokiniai5.txt vector generavimas
